name:                bbl2bib
version:             0.1.0.0
github:              "ncihnegn/bbl2bib"
license:             BSD3
author:              "ncihnegn"
maintainer:          "ncihnegn@users.noreply.github.com"
copyright:           "2020 ncihnegn"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ncihnegn/bbl2bib#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  bbl2bib-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bbl2bib

tests:
  bbl2bib-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bbl2bib
